version: '3'

services:
  service2:
    container_name: service2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - lab1_networks

networks:
  lab1_networks:
    external: true
    driver: bridge