version: '3'

services:
  service1:
    container_name: service1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - lab1_networks

networks:
  lab1_networks:
    external: true
    driver: bridge