version: '3'

services:
  service1:
    container_name: service1
    build:
      context: .
      dockerfile: service1/Dockerfile
    ports:
      - "8081:8081"

  service2:
    container_name: service2
    build:
      context: .
      dockerfile: service2/Dockerfile
    ports:
      - "8084:8084"

  nginx:
    image: nginx:latest
    container_name: nginx_lab1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service1
      - service2
    links:
      - service1
      - service2
    ports:
      - "80:80"