version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_lab1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - lab1_networks

networks:
  lab1_networks:
    external: true
    driver: bridge