pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    dir 'lab3'
                    sh 'docker compose up --build -f docker-compose.yml'
                }
            }
        }
    }
}